### ISSUE TITLE
rlog() instead of log(y+1) to standardize RNA-seq inputs

### ISSUE THREAD

**Issue by taylorreiter** [QiZhangStat/TGCnA#6]
Currently, your readme suggests normalizing RNA-seq data by `log(y+1)`. Would you be willing to recommend normalization with `DESeq2::rlog`? This function takes library size into account when performing log transformation and is useful for real RNA-seq data.

**Comment by QiZhangStat** [comment]
Good catch! Thanks. We did it as we are using a simulated count data in the demo. I have edited accordingly, and added other practical suggestions as well.
